// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tbhcyajaukyocniuugif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiaGN5YWphdWt5b2NuaXV1Z2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODY4MzMsImV4cCI6MjA2NTc2MjgzM30.AXvo1YPw_YR0q_RRCatbLbZqM_g1gnrGPy1q2qKHrMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);